In [1]:
import numpy as np

In [13]:
ar1 = np.ndarray(shape=(14000000,102),dtype='int16')
ar1.fill(11000)

In [14]:
ar1.nbytes

2856000000

In [17]:
ar2 = np.full(shape=(14000000,102),fill_value=10100,dtype='int16')

In [18]:
ar2.nbytes

2856000000

In [16]:
np.array(1).dtype

dtype('int32')

In [19]:
test1 = np.array([0,5,7,8,9])
test2 = np.array([0,2,3,4,5])

In [21]:
test1

array([0, 5, 7, 8, 9])

In [23]:
test1.shape

(5,)

In [25]:
test3 = np.array([[0,5,7,8,9],
                  [0,2,3,4,5]])

In [27]:
test3

array([[0, 5, 7, 8, 9],
       [0, 2, 3, 4, 5]])

In [28]:
test3.shape

(2, 5)

In [29]:
np.median(test1,test2)

AxisError: axis 2 is out of bounds for array of dimension 1

In [31]:
np.median(test3)

4.5

In [32]:
np.median(test3, axis=0)

array([0. , 3.5, 5. , 6. , 7. ])

In [33]:
np.median(test3, axis=1)

array([7., 3.])

In [34]:
test4 = np.array([test1,test2])

In [35]:
test4

array([[0, 5, 7, 8, 9],
       [0, 2, 3, 4, 5]])

Question: is it faster to make an array out of our list of smaller arrays, or is it faster to gradually append to the array over time?

Answer: it probably doesn't matter much. Creating the list of arrays is pretty darn fast, and making a big array out of the smaller arrays is probably just as fast as whatever swelling-an-array process I'd have to do otherwise.

Conclusion: I will program it to have lists of arrays.

In [36]:
vecs = {}

In [38]:
vecs['orange'] = np.array([[1,2,3],[8,7,6]])

In [40]:
vecs['orange']

array([[1, 2, 3],
       [8, 7, 6]])

In [43]:
vecs.keys()

dict_keys(['orange'])

In [45]:
vecs.values()

dict_values([array([[1, 2, 3],
       [8, 7, 6]])])

In [49]:
[[]] * 6

[[], [], [], [], [], []]

In [50]:
vecs2 = {'A','B','C','D','E','F'}

In [53]:
vecs2.values() = [[]] * 6

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (3475651122.py, line 1)

In [54]:
for x in vecs2:
    print(x)

F
C
D
E
A
B


In [64]:
np.array([[1,2,3],[4,np.nan,6]])

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.]])

In [61]:
empo = np.empty((4,5))

In [62]:
empo

array([[8.76791137e-312, 5.87938119e-322, 0.00000000e+000,
        0.00000000e+000,             nan],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        3.14542538e+161, 9.25845054e+242],
       [8.12591997e-096, 1.03080491e+136, 6.01347002e-154,
        5.53291072e-048, 2.18229367e-094],
       [1.43267083e+161, 2.20832505e-094, 9.80058441e+252,
        1.23971686e+224, 2.59923519e-306]])

In [68]:
ar4 = np.ndarray(shape=(5,6),dtype='int16')
ar4[:2,:].fill(660)
ar4[2:,:].fill(880)

In [ ]:
ar4[]

In [73]:
ar4[0,0] = -9999

In [74]:
ar4[4,4] = -9999

In [94]:
ar4[:,5] = -9999

In [76]:
np.median(ar4, axis=0)

array([880., 880., 880., 880., 660., 880.])

In [80]:
np.where(ar4!=-9999, np.median(ar4, axis=0), 0)

array([[  0., 880., 880., 880., 660., 880.],
       [880., 880., 880., 880., 660., 880.],
       [880., 880., 880., 880., 660., 880.],
       [880., 880., 880., 880., 660., 880.],
       [880., 880., 880., 880.,   0., 880.]])

In [ ]:
np.

In [172]:
ar4m = np.ma.array(ar4, mask=ar4==-9999)

In [173]:
ar4m

masked_array(
  data=[[--, 660, 660, 660, 660, --],
        [660, 660, 660, 660, 660, --],
        [880, 880, 880, 880, 880, --],
        [880, 880, 880, 880, 880, --],
        [880, 880, 880, 880, --, --]],
  mask=[[ True, False, False, False, False,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False, False,  True],
        [False, False, False, False,  True,  True]],
  fill_value=999999,
  dtype=int16)

In [189]:
result = np.ma.median(ar4m, axis=0).astype('int16')

In [182]:
result = np.ma.median(ar4m, axis=0)

In [190]:
result

masked_array(data=[880, 880, 880, 880, 770, --],
             mask=[False, False, False, False, False,  True],
       fill_value=999999,
            dtype=int16)

In [191]:
result.data

array([880, 880, 880, 880, 770,   0], dtype=int16)

In [192]:
filled = result.filled(-9999)

In [193]:
filled

array([  880,   880,   880,   880,   770, -9999], dtype=int16)

In [194]:
filled.dtype

dtype('int16')

In [100]:
result.nbytes

48

In [104]:
result.mask.nbytes

6

In [105]:
test6 = np.median(test3, axis=0)
test6

array([0. , 3.5, 5. , 6. , 7. ])

In [124]:
test6.astype('int16')

array([0, 3, 5, 6, 7], dtype=int16)

In [133]:
result.mask = result==770

In [134]:
result

masked_array(data=[880, 880, 880, 880, --, 0],
             mask=[False, False, False, False,  True, False],
       fill_value=999999,
            dtype=int16)

In [136]:
test7 = np.array([[1,2],[3,4]])

In [138]:
mask7 = test7 > 1

In [139]:
mask7 and True

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [144]:
'{0:b}'.format(255).zfill(8)

'11111111'

In [157]:
fmask_arr = np.array([[255,243],[80,62]])

In [153]:
f = lambda x: '{0:b}'.format(x).zfill(8)

In [155]:
f2 = lambda x: x ** 2

In [159]:
f(fmask_arr)

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [145]:
fmask_arr = np.array([[255,243],[80,62]])

binary = '{0:b}'.format(fmask_arr).zfill(8)

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [150]:
test7.shape

(2, 2)

In [161]:
boo1 = np.array([[True,False],
         [True,False]])

boo2 = np.array([[False,False],
                [True,True]])

In [163]:
boo1 | boo2

array([[ True, False],
       [ True,  True]])

In [165]:
boo1.flatten()

array([ True, False,  True, False])

In [166]:
f = lambda x: '{0:b}'.format(x).zfill(8)

In [ ]:
g = lambda x: 

In [167]:
test8 = np.array([255,80,62,202])

In [170]:
for el in test8:
    print(el)
    print(f(el))

255
11111111
80
01010000
62
00111110
202
11001010
